services:
    
  db:
    image: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  api:
    build: ./api
    command: sh ./startup-dev-server.sh
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - 9229:9229
    environment:
      - FRONTEND_PROT=${FRONTEND_PROT}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - ./api:/usr/src/app/dev
    depends_on:
      - db

  web:
    build: 
      context: ./web
    ports:
      - ${FRONTEND_PORT}:4200
    environment:
      - BACKEND_PROT=${BACKEND_PROT}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./web:/home/dev
    working_dir: /home/dev
    command: sh ./startup-dev-server.sh
    depends_on:
      - api

volumes:
  psql: