services:
    
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  api:
    build: ./api
    command: bash -c "npm run start:debug"
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - 9229:9229
    volumes:
      - ./api:/usr/src/app/dev
    depends_on:
      - db

  web:
    build: 
      context: ./web
    ports:
      - ${FRONTEND_PORT}:4200
    environment:
      - BACKEND_PROT=${BACKEND_PROT}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./web:/home/dev
    working_dir: /home/dev
    command: sh ./startup-dev-server.sh
    depends_on:
      - api

volumes:
  psql: