services:
    
  db:
    image: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  api:
    build: ./api
    command: sh -c 'cd api; ./configure.sh; npm run start:debug'
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - 9229:9229
    volumes:
      - ./:/usr/src/app/dev
    depends_on:
      - db

  web:
    build: 
      context: ./web
    working_dir: /home/dev
    command: sh -c 'cd web; sh configure.sh; ./node_modules/.bin/ng serve --host 0.0.0.0'
    ports:
      - ${FRONTEND_PORT}:4200
    volumes:
      - ./:/home/dev
    depends_on:
      - api

volumes:
  psql: