services:
    
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  api:
    build: ./api
    command: bash -c "npm run start:debug"
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./api:/usr/src/app/dev
    depends_on:
      - db

  web:
    build: ./web
    ports:
      - 80:4200
    volumes:
      - ./web:/home/dev
    working_dir: /home/dev
    command: ../node_modules/.bin/ng serve --host 0.0.0.0
    depends_on:
      - api

volumes:
  psql: