services:

  ## NGINX
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - TRUST_DOWNSTREAM_PROXY=true
    volumes:
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=admin@domain.com
    depends_on:
      - nginx-proxy
    restart: always

  ## DOCKER REGISTRY
  registry:
    image: registry
    volumes:
      - registry:/var/lib/registry
    environment:
      - VIRTUAL_HOST=registry.domain.com
      - LETSENCRYPT_HOST=registry.domain.com
      - LETSENCRYPT_EMAIL=admin@domain.com
    depends_on:
      - nginx-proxy-acme
    restart: always
  registry-local:
    image: registry
    ports:
      - 5001:5000
    volumes:
      - registry:/var/lib/registry
    restart: always

  ## JENKINS
  jenkins:
    build:
      context: ./app/prod/jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=jenkins.domain.com
      - LETSENCRYPT_HOST=jenkins.domain.com
      - LETSENCRYPT_EMAIL=admin@domain.com
      - VIRTUAL_PORT=8080
    depends_on:
      - nginx-proxy-acme
    restart: always

  ## APP
  api:
    image: localhost:5001/app/api:latest
    command: sh -c "bash -c "npm run start:prod"
    environment:
      - VIRTUAL_HOST=api.app.com
      - VIRTUAL_PORT=8010
      - LETSENCRYPT_HOST=api.olmayo.com
      - LETSENCRYPT_EMAIL=admin@domain.com
    restart: always
  web:
    image: localhost:5001/app/web:latest
    working_dir: /home/dev
    environment:
      - BACKEND_BASE_URL=api.app.com
      - VIRTUAL_HOST=app.com,www.app.com
      - LETSENCRYPT_HOST=app.com,www.app.com
      - LETSENCRYPT_EMAIL=admin@domain.com
    depends_on:
      - nginx-proxy-acme
    restart: always

  ## WATCHTOWER
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 root-api-1 root-web-1
    restart: always

volumes:
  jenkins:
  registry:
  vhost:
  html:
  certs:
  acme: