services:

  ## NGINX
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - TRUST_DOWNSTREAM_PROXY=true
    volumes:
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${DOMAIN_ADMIN}
    depends_on:
      - nginx-proxy
    restart: always

  ## DOCKER REGISTRY
  registry:
    image: registry
    ports:
      - 5001:5000
    volumes:
      - registry:/var/lib/registry
    restart: always

  ## JENKINS
  jenkins:
    build: ./jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=${DOMAIN_JENKINS}
      - LETSENCRYPT_HOST=${DOMAIN_JENKINS}
      - LETSENCRYPT_EMAIL=${DOMAIN_ADMIN}
      - VIRTUAL_PORT=8080
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - JENKINS_URL=${JENKINS_URL}
    depends_on:
      - nginx-proxy-acme
      - registry
    restart: always

  ## DATABASE
  db:
    image: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  ## APP
  api:
    image: localhost:5001/app/api:latest
    environment:
      - VIRTUAL_HOST=${BACKEND_HOST}
      - VIRTUAL_PORT=${BACKEND_PORT}
      - LETSENCRYPT_HOST=${BACKEND_HOST}
      - LETSENCRYPT_EMAIL=${DOMAIN_ADMIN}
    depends_on:
      - db
      - registry
    restart: always

  web:
    image: localhost:5001/app/web:latest
    working_dir: /home/dev
    environment:
      - VIRTUAL_HOST=${FRONTEND_HOST}
      - LETSENCRYPT_HOST=${FRONTEND_HOST}
      - LETSENCRYPT_EMAIL=${DOMAIN_ADMIN}
    depends_on:
      - nginx-proxy-acme
      - registry
    restart: always

  ## WATCHTOWER
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 prod-api-1 prod-web-1
    restart: always
    depends_on:
      - api
      - web

volumes:
  jenkins:
  registry:
  vhost:
  html:
  certs:
  acme:
  psql:
