services:

  ## NGINX
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - TRUST_DOWNSTREAM_PROXY=true
    volumes:
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${DOMAIN_ADMIN}
    depends_on:
      - nginx-proxy
    restart: always

  ## DOCKER REGISTRY
  registry:
    image: registry
    volumes:
      - registry:/var/lib/registry
    environment:
      - VIRTUAL_HOST=${DOMAIN_REGISTRY}
      - LETSENCRYPT_HOST=${DOMAIN_REGISTRY}
      - LETSENCRYPT_EMAIL=${DOMAIN_ADMIN}
    depends_on:
      - nginx-proxy-acme
    restart: always

  registry-local:
    image: registry
    ports:
      - 5001:5000
    volumes:
      - registry:/var/lib/registry
    restart: always

  ## JENKINS
  jenkins:
    build: ./jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=${DOMAIN_JENKINS}
      - LETSENCRYPT_HOST=${DOMAIN_JENKINS}
      - LETSENCRYPT_EMAIL=${DOMAIN_ADMIN}
      - VIRTUAL_PORT=8080
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - JENKINS_URL=${JENKINS_URL}
    depends_on:
      - nginx-proxy-acme
      - registry-local
      - registry
    restart: always

  ## APP
  api:
    image: localhost:5001/app/api:latest
    environment:
      - VIRTUAL_HOST=${DOMAIN_API}
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=${DOMAIN_API}
      - LETSENCRYPT_EMAIL=${DOMAIN_ADMIN}
      - FRONTEND_PROT=${FRONTEND_PROT}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SYNC=${DATABASE_SYNC}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - registry-local
    restart: always

  web:
    image: localhost:5001/app/web:latest
    working_dir: /home/dev
    environment:
      - VIRTUAL_HOST=${DOMAIN_WEB}
      - LETSENCRYPT_HOST=${DOMAIN_WEB}
      - LETSENCRYPT_EMAIL=${DOMAIN_ADMIN}
    depends_on:
      - nginx-proxy-acme
      - registry-local
    restart: always

  ## WATCHTOWER
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 prod-api-1 prod-web-1
    restart: always

volumes:
  jenkins:
  registry:
  vhost:
  html:
  certs:
  acme:
