jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
jobs:
  - file: /var/jenkins_home/job.groovy
unclassified:
  location:
    url: ${JENKINS_URL}
